// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecases/student_update.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecases/student_update.go -destination=internal/domain/mocks/student_update.go -typed=true -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dtos "github.com/dmarins/student-api/internal/domain/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockIStudentUpdateUseCase is a mock of IStudentUpdateUseCase interface.
type MockIStudentUpdateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIStudentUpdateUseCaseMockRecorder
	isgomock struct{}
}

// MockIStudentUpdateUseCaseMockRecorder is the mock recorder for MockIStudentUpdateUseCase.
type MockIStudentUpdateUseCaseMockRecorder struct {
	mock *MockIStudentUpdateUseCase
}

// NewMockIStudentUpdateUseCase creates a new mock instance.
func NewMockIStudentUpdateUseCase(ctrl *gomock.Controller) *MockIStudentUpdateUseCase {
	mock := &MockIStudentUpdateUseCase{ctrl: ctrl}
	mock.recorder = &MockIStudentUpdateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStudentUpdateUseCase) EXPECT() *MockIStudentUpdateUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIStudentUpdateUseCase) Execute(ctx context.Context, studentUpdateInput dtos.StudentUpdateInput) *dtos.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, studentUpdateInput)
	ret0, _ := ret[0].(*dtos.Result)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockIStudentUpdateUseCaseMockRecorder) Execute(ctx, studentUpdateInput any) *MockIStudentUpdateUseCaseExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIStudentUpdateUseCase)(nil).Execute), ctx, studentUpdateInput)
	return &MockIStudentUpdateUseCaseExecuteCall{Call: call}
}

// MockIStudentUpdateUseCaseExecuteCall wrap *gomock.Call
type MockIStudentUpdateUseCaseExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIStudentUpdateUseCaseExecuteCall) Return(arg0 *dtos.Result) *MockIStudentUpdateUseCaseExecuteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIStudentUpdateUseCaseExecuteCall) Do(f func(context.Context, dtos.StudentUpdateInput) *dtos.Result) *MockIStudentUpdateUseCaseExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIStudentUpdateUseCaseExecuteCall) DoAndReturn(f func(context.Context, dtos.StudentUpdateInput) *dtos.Result) *MockIStudentUpdateUseCaseExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
