basePath: /
definitions:
  dtos.Result:
    properties:
      data: {}
      message:
        type: string
    type: object
  dtos.StudentCreateInput:
    properties:
      name:
        maxLength: 200
        type: string
    required:
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an example API written in Go.
  title: Student Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      description: Checks if the API has connectivity to your database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.Result'
      summary: Check if the API is available.
      tags:
      - health
  /students:
    post:
      consumes:
      - application/json
      description: Allows you to create a student after validating duplicate names.
      parameters:
      - description: To identify the tenant
        in: header
        name: x-tenant
        required: true
        type: string
      - description: To identify the request
        in: header
        name: x-cid
        type: string
      - description: To create a student
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dtos.StudentCreateInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.Result'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.Result'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dtos.Result'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.Result'
      summary: Allows you to create a student.
      tags:
      - students
schemes:
- http
swagger: "2.0"
